# Use this file to control the main attributes of the website

# You
name: Homin Lee

# Title for your site as it will appear in google
# e.g. Resume, Curriculum Vitae, Work History
title: Homin Lee
title2: Accomplished Software Engineer

# SEO description
description: Digital resume for Homin Lee.

# URL of this resume
url: "https://homin.dev/resume/"
baseurl: "./"

# URL of your personal website (make same as URL if you don't have one)
personal: "https://homin.dev"

# these should be pretty self-explanatory :-P
email: ff4500@gmail.com
twitter: suapapa

# Show this in the footer
# copyright: Homin Lee &lt;homin.lee@suapapa.net&gt; All rights reserved.
copyright: Homin Lee <ff4500@gmail.com>; All rights reserved.

# What should the navigation be called?
navigation: navigation

# Google analytics ID: UA-XXXXX-X
analytics: UA-65909718-1
