# Use this file to control the main attributes of the website

# You
name: Homin Lee

# Title for your site as it will appear in google
# e.g. Resume, Curriculum Vitae, Work History
title: Homin Lee
title2: A Go System Software Engineer

# SEO description
description: Digital resume for Homin Lee.

# URL of this resume
url: "https://suapapa.github.io/resume/"
baseurl: "https://suapapa.github.io/resume/"
# baseurl: "./"

# URL of your personal website (make same as URL if you don't have one)
personal: "http://suapapa.net"

# these should be pretty self-explanatory :-P
email: homin.lee@suapapa.net
twitter: suapapa

# Show this in the footer
# copyright: Homin Lee &lt;homin.lee@suapapa.net&gt; All rights reserved.
copyright: Homin Lee <homin.lee@suapapa.net>; All rights reserved.

# What should the navigation be called?
navigation: navigation

# Google analytics ID: UA-XXXXX-X
analytics: UA-65909718-1
